version: '3.7'

services:


  spring-cloud-config-server:
    image: 11716265/ecp-spring-cloud-config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - commerce-network
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/SabahTARTIR365/config-data

  shop-service:
    image: 11716265/ecp-shop-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9002:9002"
    networks:
      - commerce-network
    depends_on:
      - naming-server
      - shop-db
      - spring-cloud-config-server
    
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://shop-db:3306/ecommerce_system_shop
      SPRING.DATASOURCE.USERNAME: springstudent
      SPRING.DATASOURCE.PASSWORD: springstudent
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING.JPA.HIBERNATE.DDL-AUTO: update

  wallet-service:
    image: 11716265/ecp-wallet-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9003:9003"
    networks:
      - commerce-network
    depends_on:
      - naming-server
      - wallet-db
      - spring-cloud-config-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://wallet-db:3306/ecommerce_system
      SPRING.DATASOURCE.USERNAME: springstudent
      SPRING.DATASOURCE.PASSWORD: springstudent
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING.JPA.HIBERNATE.DDL-AUTO: update

  inventory-service:
    image: 11716265/ecp-inventory-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9001:9001"
    networks:
      - commerce-network
    depends_on:
      - naming-server
      - inventory-db
      - spring-cloud-config-server
      
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://inventory-db:3306/ecommerce_system_inventory
      SPRING.DATASOURCE.USERNAME: springstudent
      SPRING.DATASOURCE.PASSWORD: springstudent
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING.JPA.HIBERNATE.DDL-AUTO: update
    
    

  api-gateway-ejada:
    image: 11716265/ecp-api-gateway-ejada:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - commerce-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      

  naming-server:
    image: 11716265/ecp-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - commerce-network


  wallet-db:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    networks:
      - commerce-network
    environment:
      MYSQL_ROOT_PASSWORD: 11716265Ss+
      MYSQL_DATABASE: ecommerce_system
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    volumes:
      - wallet-db-data:/var/lib/mysql

  shop-db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    networks:
      - commerce-network
    environment:
      MYSQL_ROOT_PASSWORD: 11716265Ss+
      MYSQL_DATABASE: ecommerce_system_shop
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    volumes:
      - shop-db-data:/var/lib/mysql

  inventory-db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - commerce-network
    environment:
      MYSQL_ROOT_PASSWORD: 11716265Ss+
      MYSQL_DATABASE: ecommerce_system_inventory
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    volumes:
      - inventory-db-data:/var/lib/mysql

networks:
  commerce-network:

volumes:
  wallet-db-data:
  shop-db-data:
  inventory-db-data: